// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    PjCodeBlock: typeof import('./components/PjCodeBlock.vue')['default']
    PjFooter: typeof import('./components/PjFooter.vue')['default']
    PjHeader: typeof import('./components/PjHeader.vue')['default']
    PjNavbar: typeof import('./components/PjNavbar.vue')['default']
    PjSidebar: typeof import('./components/PjSidebar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VvAccordion: typeof import('@volverjs/ui-vue/vv-accordion')['default']
    VvAction: typeof import('@volverjs/ui-vue/vv-action')['default']
    VvButton: typeof import('@volverjs/ui-vue/vv-button')['default']
    VvCard: typeof import('@volverjs/ui-vue/vv-card')['default']
    VvInputText: typeof import('@volverjs/ui-vue/vv-input-text')['default']
  }
}
